TableMap {
  timestamp: 1460061219000,
  nextPosition: 6373,
  size: 77,
  tableMap:
   { '70':
      { columnSchemas: [Object],
        parentSchema: 'menuweb',
        tableName: 'mewpae',
        columns: [Object] },
     '71':
      { columnSchemas: [Object],
        parentSchema: 'menuweb',
        tableName: 'mewpae',
        columns: [Object] } },
  tableId: 70,
  flags: 1,
  schemaName: 'menuweb',
  tableName: 'mewpae',
  columnCount: 21,
  columnTypes: [ 3, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 3, 3, 3, 3, 3, 3, 3 ],
  columnsMetadata:
   [ undefined,
     { max_length: 5 },
     { max_length: 5 },
     { max_length: 5 },
     { max_length: 500 },
     { max_length: 15 },
     { max_length: 50 },
     { max_length: 7 },
     { max_length: 7 },
     { max_length: 7 },
     { max_length: 7 },
     { max_length: 7 },
     { max_length: 7 },
     { max_length: 7 },
     undefined,
     undefined,
     undefined,
     undefined,
     undefined,
     undefined,
     undefined ] }
UpdateRows {
  _hasTwoRows: true,
  timestamp: 1460061219000,
  nextPosition: 7135,
  size: 739,
  _zongji:
   ZongJi {
     options: { includeEvents: [Object], includeSchema: [Object] },
     domain: null,
     _events: { binlog: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     ctrlConnection:
      Connection {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        config: [Object],
        _socket: [Object],
        _protocol: [Object],
        _connectCalled: true,
        state: 'authenticated',
        threadId: 26 },
     ctrlCallbacks: [ [Function] ],
     connection:
      Connection {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        config: [Object],
        _socket: [Object],
        _protocol: [Object],
        _connectCalled: true,
        state: 'authenticated',
        threadId: 27 },
     tableMap: { '70': [Object], '71': [Object] },
     ready: true,
     useChecksum: true,
     binlog: { [Function: Binlog] super_: [Object] } },
  tableId: 70,
  flags: 1,
  useChecksum: true,
  extraDataLength: 2,
  numberOfColumns: 21,
  tableMap:
   { '70':
      { columnSchemas: [Object],
        parentSchema: 'menuweb',
        tableName: 'mewpae',
        columns: [Object] },
     '71':
      { columnSchemas: [Object],
        parentSchema: 'menuweb',
        tableName: 'mewpae',
        columns: [Object] } },
  rows: [ { before: [Object], after: [Object] } ] }